# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    pip install databricks-cli
    databricks configure --token https://eastus2.azuredatabricks.net dapi883576c6204113b7e4a8b09f3d717444
    databricks jobs run-now --job-id 3
  displayName: 'Run a multi-line script'
