# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: pip install databricks-cli
  displayName: 'Install CLI'

- script: databricks configure --token https://eastus2.azuredatabricks.net dapi883576c6204113b7e4a8b09f3d717444
  displayName: 'Configure Repo'

- script: databricks jobs run-now --job-id 3
  displayName: 'Run notebook'
